# Generated by Django 4.0.4 on 2025-04-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0005_alter_movie_actors_alter_movie_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(to="cinema.actor"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(to="cinema.genre"),
        ),
    ]
